name: Windows g++ sstream
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022]
    steps:
      - uses: actions/checkout@v3
      - run: gcc --version
      - run: g++ -O0 -o sstream sstream.cpp -std=gnu++17
      - run: ./sstream
