name: Windows g++ sstream
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022]
    steps:
      - uses: actions/checkout@v3
      - run: g++ --version
      - run: g++ -O0 -o sstream.exe sstream.cpp -std=gnu++17
      - run: ls -l | grep sstream
      - run: ./sstream
