name: Windows g++ sstream
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022]
    steps:
      - uses: actions/checkout@v3
      - run: echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $Env:GITHUB_PATH
      - run: $Env:GITHUB_PATH
      - run: ls C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin
      - run: g++ --version
      - run: g++ -O0 -o sstream sstream.cpp -std=gnu++17
      - run: ls
      - run: ./sstream
